// <auto-generated />
using System;
using Maranny.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maranny.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212135424_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Maranny.Core.Entities.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("F_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("L_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdminID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Maranny.Core.Entities.AdminPhone", b =>
                {
                    b.Property<int>("AdminID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.HasKey("AdminID", "Phone");

                    b.ToTable("AdminPhones");
                });

            modelBuilder.Entity("Maranny.Core.Entities.AdminProduct", b =>
                {
                    b.Property<int>("AdminID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ProductID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("AdminID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("AdminProducts");
                });

            modelBuilder.Entity("Maranny.Core.Entities.AdminReport", b =>
                {
                    b.Property<int>("ReportID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("AdminID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ReportID", "AdminID");

                    b.HasIndex("AdminID");

                    b.ToTable("AdminReports");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Maranny.Core.Entities.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("ClientID");

                    b.HasIndex("SessionID")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MainCategoryID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("MainCategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientID"));

                    b.Property<string>("Build_num")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("F_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("bit");

                    b.Property<string>("L_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street_name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("URL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClientID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientAdmin", b =>
                {
                    b.Property<int>("ClientID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("AdminID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ClientID", "AdminID");

                    b.HasIndex("AdminID");

                    b.ToTable("ClientAdmins");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientNotification", b =>
                {
                    b.Property<int>("ClientID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("NotificationID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ClientID", "NotificationID");

                    b.HasIndex("NotificationID");

                    b.ToTable("ClientNotifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientPhone", b =>
                {
                    b.Property<int>("ClientID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(1);

                    b.HasKey("ClientID", "Phone");

                    b.ToTable("ClientPhones");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientRecommendation", b =>
                {
                    b.Property<int>("ClientID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RecommendationID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientID", "RecommendationID");

                    b.HasIndex("RecommendationID");

                    b.ToTable("ClientRecommendations");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientReport", b =>
                {
                    b.Property<int>("ClientID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ReportID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ClientID", "ReportID");

                    b.HasIndex("ReportID");

                    b.ToTable("ClientReports");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientSession", b =>
                {
                    b.Property<int>("ClientID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("SessionID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ClientID", "SessionID");

                    b.HasIndex("SessionID");

                    b.ToTable("ClientSessions");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Coach", b =>
                {
                    b.Property<int>("CoachID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachID"));

                    b.Property<string>("AvailabilityStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("AvgRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("F_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("L_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("URL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("CoachID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachAdmin", b =>
                {
                    b.Property<int>("AdminID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("CoachID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("AdminID", "CoachID");

                    b.HasIndex("CoachID");

                    b.ToTable("CoachAdmins");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachClient", b =>
                {
                    b.Property<int>("ClientID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("CoachID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ClientID", "CoachID");

                    b.HasIndex("CoachID");

                    b.ToTable("CoachClients");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachLocation", b =>
                {
                    b.Property<int>("CoachID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("WorkingLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(1);

                    b.HasKey("CoachID", "WorkingLocation");

                    b.ToTable("CoachLocations");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachNotification", b =>
                {
                    b.Property<int>("CoachID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("NotificationID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("CoachID", "NotificationID");

                    b.HasIndex("NotificationID");

                    b.ToTable("CoachNotifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachSport", b =>
                {
                    b.Property<int>("CoachSportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachSportID"));

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<decimal?>("PricePerSession")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.HasKey("CoachSportID");

                    b.HasIndex("SportID");

                    b.HasIndex("CoachID", "SportID")
                        .IsUnique();

                    b.ToTable("CoachSports");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PaymentID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("AdminID");

                    b.HasIndex("BookingID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ReviewID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentGateway")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PlatformFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentID");

                    b.HasIndex("BookingID");

                    b.HasIndex("ClientID");

                    b.HasIndex("SessionID")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("URL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ClientID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Recommendation", b =>
                {
                    b.Property<int>("RecommendationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationID"));

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("RecommendationID");

                    b.HasIndex("CoachID");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("Maranny.Core.Entities.RecommendedSport", b =>
                {
                    b.Property<int>("RecommendationID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("SportID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("RecommendationID", "SportID");

                    b.HasIndex("SportID");

                    b.ToTable("RecommendedSports");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReportedType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReporterType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("CoachID");

                    b.HasIndex("ProductID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ReportNotification", b =>
                {
                    b.Property<int>("ReportID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("NotificationID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ReportID", "NotificationID");

                    b.HasIndex("NotificationID");

                    b.ToTable("ReportNotifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("ClientID");

                    b.HasIndex("CoachID");

                    b.HasIndex("SessionID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SportId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SportName");

                    b.Property<int>("PopularityScore")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("Maranny.Core.Entities.SportProduct", b =>
                {
                    b.Property<int>("SportID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ProductID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("SportID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("SportProducts");
                });

            modelBuilder.Entity("Maranny.Core.Entities.TrainingSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("End_Time")
                        .HasColumnType("time");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Start_Time")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SessionID");

                    b.HasIndex("CoachID");

                    b.HasIndex("SportID");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("Maranny.Core.Entities.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BudgetMax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("BudgetMin")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MaxDistance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Sports")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Maranny.Core.Entities.Admin", b =>
                {
                    b.HasOne("Maranny.Core.Entities.ApplicationUser", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Maranny.Core.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Maranny.Core.Entities.AdminPhone", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Admin", "Admin")
                        .WithMany("AdminPhones")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Maranny.Core.Entities.AdminProduct", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Admin", "Admin")
                        .WithMany("AdminProducts")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Product", "Product")
                        .WithMany("AdminProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Maranny.Core.Entities.AdminReport", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Admin", "Admin")
                        .WithMany("AdminReports")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Report", "Report")
                        .WithMany("AdminReports")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Booking", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.TrainingSession", "TrainingSession")
                        .WithOne("Booking")
                        .HasForeignKey("Maranny.Core.Entities.Booking", "SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Category", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Category", "MainCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("MainCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Client", b =>
                {
                    b.HasOne("Maranny.Core.Entities.ApplicationUser", "User")
                        .WithOne("Client")
                        .HasForeignKey("Maranny.Core.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientAdmin", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Admin", "Admin")
                        .WithMany("ClientAdmins")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("ClientAdmins")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientNotification", b =>
                {
                    b.HasOne("Maranny.Core.Entities.ApplicationUser", "Client")
                        .WithMany("ClientNotifications")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Notification", "Notification")
                        .WithMany("ClientNotifications")
                        .HasForeignKey("NotificationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientPhone", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("ClientPhones")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientRecommendation", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("ClientRecommendations")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Recommendation", "Recommendation")
                        .WithMany("ClientRecommendations")
                        .HasForeignKey("RecommendationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientReport", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("ClientReports")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Report", "Report")
                        .WithMany("ClientReports")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ClientSession", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("ClientSessions")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.TrainingSession", "TrainingSession")
                        .WithMany("ClientSessions")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Coach", b =>
                {
                    b.HasOne("Maranny.Core.Entities.ApplicationUser", "User")
                        .WithOne("Coach")
                        .HasForeignKey("Maranny.Core.Entities.Coach", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachAdmin", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Admin", "Admin")
                        .WithMany("CoachAdmins")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Coach", "Coach")
                        .WithMany("CoachAdmins")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachClient", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("CoachClients")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Coach", "Coach")
                        .WithMany("CoachClients")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachLocation", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Coach", "Coach")
                        .WithMany("CoachLocations")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachNotification", b =>
                {
                    b.HasOne("Maranny.Core.Entities.ApplicationUser", "Coach")
                        .WithMany("CoachNotifications")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Notification", "Notification")
                        .WithMany("CoachNotifications")
                        .HasForeignKey("NotificationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Maranny.Core.Entities.CoachSport", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Coach", "Coach")
                        .WithMany("CoachSports")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Sport", "Sport")
                        .WithMany("CoachSports")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Notification", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Admin", "Admin")
                        .WithMany("Notifications")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maranny.Core.Entities.Booking", "Booking")
                        .WithMany("Notifications")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maranny.Core.Entities.Payment", "Payment")
                        .WithMany("Notifications")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maranny.Core.Entities.Product", "Product")
                        .WithMany("Notifications")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Maranny.Core.Entities.Review", "Review")
                        .WithMany("Notifications")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");

                    b.Navigation("Booking");

                    b.Navigation("Payment");

                    b.Navigation("Product");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Payment", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.TrainingSession", "TrainingSession")
                        .WithOne("Payment")
                        .HasForeignKey("Maranny.Core.Entities.Payment", "SessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Client");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Product", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("Products")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Recommendation", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Coach", "Coach")
                        .WithMany("Recommendations")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Maranny.Core.Entities.RecommendedSport", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Recommendation", "Recommendation")
                        .WithMany("RecommendedSports")
                        .HasForeignKey("RecommendationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Sport", "Sport")
                        .WithMany("RecommendedSports")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recommendation");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Report", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ReportNotification", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Notification", "Notification")
                        .WithMany("ReportNotifications")
                        .HasForeignKey("NotificationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Report", "Report")
                        .WithMany("ReportNotifications")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Review", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Coach", "Coach")
                        .WithMany("Reviews")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.TrainingSession", "TrainingSession")
                        .WithMany("Reviews")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coach");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("Maranny.Core.Entities.SportProduct", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Product", "Product")
                        .WithMany("SportProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Sport", "Sport")
                        .WithMany("SportProducts")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Maranny.Core.Entities.TrainingSession", b =>
                {
                    b.HasOne("Maranny.Core.Entities.Coach", "Coach")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.Sport", "Sport")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Maranny.Core.Entities.UserPreferences", b =>
                {
                    b.HasOne("Maranny.Core.Entities.ApplicationUser", "User")
                        .WithOne("UserPreferences")
                        .HasForeignKey("Maranny.Core.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Maranny.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Maranny.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maranny.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Maranny.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maranny.Core.Entities.Admin", b =>
                {
                    b.Navigation("AdminPhones");

                    b.Navigation("AdminProducts");

                    b.Navigation("AdminReports");

                    b.Navigation("ClientAdmins");

                    b.Navigation("CoachAdmins");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Client");

                    b.Navigation("ClientNotifications");

                    b.Navigation("Coach");

                    b.Navigation("CoachNotifications");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Booking", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Client", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ClientAdmins");

                    b.Navigation("ClientPhones");

                    b.Navigation("ClientRecommendations");

                    b.Navigation("ClientReports");

                    b.Navigation("ClientSessions");

                    b.Navigation("CoachClients");

                    b.Navigation("Payments");

                    b.Navigation("Products");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Coach", b =>
                {
                    b.Navigation("CoachAdmins");

                    b.Navigation("CoachClients");

                    b.Navigation("CoachLocations");

                    b.Navigation("CoachSports");

                    b.Navigation("Recommendations");

                    b.Navigation("Reviews");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Notification", b =>
                {
                    b.Navigation("ClientNotifications");

                    b.Navigation("CoachNotifications");

                    b.Navigation("ReportNotifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Payment", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Product", b =>
                {
                    b.Navigation("AdminProducts");

                    b.Navigation("Notifications");

                    b.Navigation("SportProducts");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Recommendation", b =>
                {
                    b.Navigation("ClientRecommendations");

                    b.Navigation("RecommendedSports");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Report", b =>
                {
                    b.Navigation("AdminReports");

                    b.Navigation("ClientReports");

                    b.Navigation("ReportNotifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Review", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Maranny.Core.Entities.Sport", b =>
                {
                    b.Navigation("CoachSports");

                    b.Navigation("RecommendedSports");

                    b.Navigation("SportProducts");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("Maranny.Core.Entities.TrainingSession", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("ClientSessions");

                    b.Navigation("Payment");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
